project:
  type: website
  output-dir: _site

website:
  title: "Daniel A. Bolivar"
  #favicon: "fa-duotone fa-dna"
  #navbar:
  #  right:
  #    - href: index.qmd
  #      text: ""
      #- about.qmd
      #- publications.qmd

format:
  html:
    theme: materia # default cerulean cosmo cyborg darkly flatly 
                   # journal litera lumen lux materia minty 
                   # morph pulse quartz sandstone simplex sketchy
                   # slate solar spacelab superhero united vapor yeti zephyr
    css: styles.css
    toc: true
    toc-location: right
    toc-title: " "  
    number-sections: false
    code-copy: true

#editor: visual